/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asj;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
